"""Add booking and transaction models

Revision ID: 163569b7f9ca
Revises: fde8450c9204
Create Date: 2025-07-09 08:21:34.447923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163569b7f9ca'
down_revision = 'fde8450c9204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Enum('AIR', 'COACH', 'TRAIN', name='travelmode'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
