"""Added Avenue Model

Revision ID: 208442e53b5b
Revises: 08a7e68f56f6
Create Date: 2025-07-02 07:57:15.894464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208442e53b5b'
down_revision = '08a7e68f56f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_destination_id', sa.Integer(), nullable=False),
    sa.Column('arrive_destination_id', sa.Integer(), nullable=False),
    sa.Column('leave_time', sa.Time(), nullable=False),
    sa.Column('arrive_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arrive_destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['leave_destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avenues')
    # ### end Alembic commands ###
