"""Added Faqs

Revision ID: 2b7652ee178b
Revises: 228f7e7cbac9
Create Date: 2025-07-01 15:58:13.799293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7652ee178b'
down_revision = '228f7e7cbac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='globalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faqs')
    # ### end Alembic commands ###
