"""Adding ticket column on Booking

Revision ID: 8cd28819aecf
Revises: e55f5ee08f59
Create Date: 2025-07-10 07:41:58.203869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd28819aecf'
down_revision = 'e55f5ee08f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('avenue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.Enum('AIR', 'COACH', 'TRAIN', name='travelmode'), nullable=False),
    sa.Column('type', sa.Enum('ECONOMY', 'BUSINESS', 'FIRST', name='seatclass'), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', 'PENDING', name='bookingstatus'), nullable=False),
    sa.Column('ticket', sa.Enum('SCANNED', 'UNSCANNED', name='scannedstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['avenue_id'], ['avenues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('PAYPAL', 'REVOLUT', 'STRIPE', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='transactionstatus'), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('bookings')
    # ### end Alembic commands ###
