"""Added Avenue Model

Revision ID: b3b7d96a6248
Revises: 208442e53b5b
Create Date: 2025-07-02 07:59:08.642006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b7d96a6248'
down_revision = '208442e53b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_destination_id', sa.Integer(), nullable=False),
    sa.Column('arrive_destination_id', sa.Integer(), nullable=False),
    sa.Column('leave_time', sa.Time(), nullable=False),
    sa.Column('arrive_time', sa.Time(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='globalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arrive_destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['leave_destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avenues')
    # ### end Alembic commands ###
